apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-a
  namespace: eks-tissue-2-cell-1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: svc-a
  template:
    metadata:
      labels:
        app: svc-a
    spec:
      containers:
        - image: kong/go-echo:latest
          name: svc-a
          ports:
            - containerPort: 80
