apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: eks-tissue-2-cell-2
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: kong/go-echo:latest
          name: webapp
          ports:
            - containerPort: 80
